### ISSUE TITLE
Keypad requirements

### ISSUE THREAD

**Issue by pjf** [PopUpPlayground/room-service#1]
Keypad specs:
- 12 key (0-9, *, #)
- Must look cool (sample attached)
- Slight preference for 7-pin (x,y) models, versus 12-pin (individual key) models. We're unlikely to use multi-touch.

---

![keypad2](https://cloud.githubusercontent.com/assets/12072/17724525/246c75d6-6486-11e6-98c2-90b3889297f1.jpeg)

**Comment by pjf** [comment]
This keypad [from jaycar](http://www.jaycar.com.au/12-key-numeric-keypad/p/SP0770) is $9, and looks good to me. :)

![keypad3](https://cloud.githubusercontent.com/assets/12072/17724594/b7232546-6486-11e6-8b01-b9f5cbd313b3.jpg)

**Comment by KangaBounce** [comment]
Jaycar keypad looks great!

**Comment by pjf** [comment]
Note: We're going to star as reset, hash as execute (coding).

**Comment by pjf** [comment]
I have the Jaycar keypad working ( #14, 213365fc08fd182e1176cfbd6afdc8c4fe0e40ae). The keys are rated to 1,000,000 keypresses. Assuming a typical game has a thousand key-presses, the pad should last a thousand games.

We may still go with another keypad for stylistic issues, but paying $9 every thousand games for keypad replacement is a really nice starting point. :)

**Comment by pjf** [comment]
The $9 keypad is working great.
