### ISSUE TITLE
Toughening up the electronics

### ISSUE THREAD

**Issue by pjf** [PopUpPlayground/room-service#28]
Mostly for @KangaBounce , but CC'ing in @Sayraphim just in case:

---

Right now the electronics we've got are a bit fragile. There are three things I'd like to do in order to toughen them up:

**Replacing serial connections between the drivers with a dedicated buses**

The only cable between our TLC5947 drivers that _needs_ to be connected in serial is the data-in/data-out cable. The rest (+5V, GND, CLK, LAT, OE) are all wired through, but they build up a significant resistance along the way (3 ohms!) which is causing all sorts of glitching. I'd like for us to have dedicated [bus bars](http://www.jaycar.com.au/machined-brass-busbar-8-way/p/SZ2003) for _at least_ +5V and GND. I'd also _love_ to add buses for CLK, LAT, OE, and +3.3V (from the controller) as they've all got multiple connections over the place, and we're not exactly restrained by small spaces.

In this scenario we'd have a star configuration for the wiring (everything but data going back to their appropriate bus) rather than a serial configuration, so if something goes wrong it will be very obvious what that something is. Wires would just go directly from the bus to the input (or output) on the boards. This should also drop our resistances _way_ down, which is particularly important for power. Data-in/data-out still needs to go serially between the boards.

Ideally we'd solder the connections in at the controllers, but we can leave them as plugs for a first pass, and possibly permanently if they're stable enough.

I'd be directly screwing the power supply to the +5V and GND bus rails, so we're not worried about joints in the connector.

**Adding a power capacitor**

I'm not at all convinced the power in the building is at all clean, given that we switched on the main lights and it resulted in pretty artefacts on the majordomo board. Putting a [power conditioning capacitor](http://www.jaycar.com.au/10000uf-40vdc-electrolytic-rp-capacitor/p/RU6720) across the +5V and GND buses will resist any oddities that we might get passed through to our hardware.

We need to make sure we don't install the cap backwards. :)

**Comment by pjf** [comment]
Turns out the buses make everything _waaaaay_ more robust. Switching the main lights on and off have no effect on the board, so we're clean enough without a power cap for now. Resolving with great thanks to @KangaBounce for doing such super-amazing work! <3

**Comment by KangaBounce** [comment]
I wish it was neater @pjf haha
