### ISSUE TITLE
Drivers for lights

### ISSUE THREAD

**Issue by pjf** [PopUpPlayground/room-service#5]
We're likely to need a boatload of shift registers or other circuitry to control the scores of lights we'll be operating.

The [74HC164](http://www.jaycar.com.au/74hc164-8-bit-serial-in-out-shift-register-ic/p/ZC4857) serial-in, parallel-out shift registers are $1.75 each, and look like they can run off a supply voltage of anywhere from 2V to 7V, so they're probably good for our needs (anticipating a 3.3V microcontroller, but maybe a 5V one).

---

Status: Tested a [TLC5947](https://www.adafruit.com/product/1429) from AdaFruit. Have many more on order.

**Comment by pjf** [comment]
Other (probably better) options:
- [STP16CP05](http://www.st.com/content/ccc/resource/technical/document/datasheet/f2/92/00/f9/dd/4a/43/22/CD00126634.pdf/files/CD00126634.pdf/jcr:content/translations/en.CD00126634.pdf) runs up to 16 lights at 100mA, as a shift register.
- [TLC59116](http://www.ti.com/lit/ds/symlink/tlc59116.pdf) runs up to 16 lights up to 120mA @17V as an I2C controller. 3.3 and 5V compatible, _and_ supports PWM.

TLC59116 looks like it's winning hardware wise.

**Comment by pjf** [comment]
OMG, the TLC59116 is a low-side driver that lets us push up to 17V through the load. Duck yes.

**Comment by pjf** [comment]
https://www.adafruit.com/product/1429 lets us control up to 30mA with 24 lines out, based on the TLC5947 chip. It's an SPI using shift register with PWM support.

Most importantly, it has nice pitch. I like the TLC59116 more, but this is something we could reasonably solder. :)

**Comment by pjf** [comment]
LittleBird has the [TLC5947](https://littlebirdelectronics.com.au/products/adafruit-24-channel-12-bit-pwm-led-driver-spi-interface-tlc5947) controllers from AdaFruit, so these are currently winning despite not being I2C.

**Comment by pjf** [comment]
Have ordered a TLC5947 from LittleBird to test with.

**Comment by pjf** [comment]
LittleBird don't have the TLC5947 in stock. I've asked how long a wait we're looking for; we may switch drivers if it's too long.

**Comment by pjf** [comment]
TronixLabs has a TLC5947; on way! :)

**Comment by pjf** [comment]
After diagnosing a poorly soldered joint on the controller I was using, I was able to get the TLC5947 to work beautifully as a driver. The programming is very straightforward using the library from AdaFruit:

``` C++
void loop() {

  // Turn all the lights on to full
  for (int i=0; i <= 23; i++) {
    tlc.setPWM(i, 4095);
  }
  tlc.write(); // Sends cmd to board
  digitalWrite(pwr,HIGH); // Set diagnostic LED on teensy

  delay(1000);

// Turn all the lights off again.
  for (int i=0; i <= 23; i++) {
    tlc.setPWM(i, 0);
  }
  tlc.write();

  digitalWrite(pwr,LOW);
  delay(500);
}
```

Github support videos, but imagine this is doing this blinking thing:

![2016-08-28 23 58 53](https://cloud.githubusercontent.com/assets/12072/18034254/96e91ff8-6d7b-11e6-9f4c-b9e842c3e01d.jpg)

Pulse-width modulation (PWM) also works a treat, so we can get different intensities which means we can try for special effects like flickering, or just the ability to manually control the light intensity.

@Sayraphim has given me the go-ahead to order more drivers if tests are successful, and since they are I'm doing that now and marking this as resolved. :) Expecting a little over a week to get them from LittleBird.

CC'ing in @KangaBounce to show we're making progress, even though I've been snowed under with book edits and talk-writing the last week. :)

**Comment by KangaBounce** [comment]
Great work @pjf :)
